# Generated by Django 3.0.3 on 2020-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='recordings',
            field=models.ManyToManyField(blank=True, to='ivr.Recording'),
        ),
    ]
