# Generated by Django 3.2 on 2021-12-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0002_auto_20200218_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
